import { Poppins, Headland_One } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "500", "700"],
  display: 'swap',
});

const headlandOne = Headland_One({
  variable: "--font-playfair",
  weight: ["400"],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${headlandOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
